Repository Nexters/Bottles_BE, pull requests merged in 2024-08, with the labels that each got.

#114 [Fix/113] Bottle 테이블 ddl을 수정한다
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/resources/sql/ddl/table_query.sql
Labels: fix 🛠️

#116 [Feature/115] refreshToken 응답시 refreshToken도 반환
  src/main/kotlin/com/nexters/bottles/auth/controller/AuthController.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/AuthFacade.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/dto/RefreshAccessTokenResponse.kt
  src/main/kotlin/com/nexters/bottles/config/SwaggerConfig.kt
  src/main/kotlin/com/nexters/bottles/config/WebConfig.kt
  src/main/kotlin/com/nexters/bottles/global/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/nexters/bottles/global/interceptor/RefreshAuthInterceptor.kt
  src/main/kotlin/com/nexters/bottles/global/interceptor/RefreshAuthRequired.kt
Labels: fix 🛠️

#120 [Feature/119] 데일리 스크럼봇 구현
  .github/workflows/daily-scrum-notification.yml
Labels: feat 💡

#122 [Feature/121] 크론 수정
  .github/workflows/daily-scrum-notification.yml
Labels: fix 🛠️

#126 [Feature/125] 유효시간 입력받아 토큰 발급받는 API를 구현한다
  src/main/kotlin/com/nexters/bottles/admin/component/TestJwtTokenProvider.kt
  src/main/kotlin/com/nexters/bottles/admin/controller/AdminController.kt
  src/main/kotlin/com/nexters/bottles/admin/facade/AdminFacade.kt
  src/main/kotlin/com/nexters/bottles/admin/facade/dto/CreateCustomTokenRequest.kt
  src/main/kotlin/com/nexters/bottles/admin/facade/dto/CustomTokenResponse.kt
Labels: admin

#128 [Feature/127] 스크럼 봇 테스트
  .github/workflows/daily-scrum-notification.yml
Labels: fix 🛠️

#112 [Feature/110] 카카오 회원가입하고 프로필 작성한 상태 만들어주기
  src/main/kotlin/com/nexters/bottles/admin/controller/AdminController.kt
  src/main/kotlin/com/nexters/bottles/admin/facade/AdminFacade.kt
  src/main/kotlin/com/nexters/bottles/admin/facade/dto/ForceAfterProfileResponse.kt
  src/main/kotlin/com/nexters/bottles/admin/service/AdminService.kt
Labels: admin

#131 [Feature/130] 액세스 토큰 만료 로직 추가 및 토큰 만료시키는 API를 구현한다
  src/main/kotlin/com/nexters/bottles/admin/controller/AdminController.kt
  src/main/kotlin/com/nexters/bottles/admin/facade/AdminFacade.kt
  src/main/kotlin/com/nexters/bottles/admin/facade/dto/ExpireTokenRequest.kt
  src/main/kotlin/com/nexters/bottles/admin/service/AdminService.kt
  src/main/kotlin/com/nexters/bottles/auth/component/JwtTokenProvider.kt
  src/main/kotlin/com/nexters/bottles/auth/controller/AuthController.kt
  src/main/kotlin/com/nexters/bottles/auth/domain/BlackList.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/AuthFacade.kt
  src/main/kotlin/com/nexters/bottles/auth/repository/BlackListRepository.kt
  src/main/kotlin/com/nexters/bottles/auth/service/BlackListService.kt
  src/main/kotlin/com/nexters/bottles/config/SwaggerConfig.kt
  src/main/kotlin/com/nexters/bottles/config/WebConfig.kt
  src/main/kotlin/com/nexters/bottles/global/resolver/AccessToken.kt
  src/main/kotlin/com/nexters/bottles/global/resolver/AccessTokenArgumentResolver.kt
  src/main/resources/sql/ddl/table_query.sql
Labels: feat 💡, admin

#133 [Feature/132] 크론식 수정
  .github/workflows/daily-scrum-notification.yml
Labels: feat 💡

#135 [Feature/134] 스크럼 내용 및 봇 수정
  .github/workflows/daily-scrum-notification.yml
Labels: feat 💡

#137 [Feature/136] 유저 정보 제공
  src/main/kotlin/com/nexters/bottles/user/controller/UserProfileController.kt
  src/main/kotlin/com/nexters/bottles/user/facade/UserProfileFacade.kt
  src/main/kotlin/com/nexters/bottles/user/facade/dto/UserInfoResponse.kt
Labels: feat 💡

#80 [Feature/36] 보틀 랜덤 매칭 기능을 구현한다
  src/main/kotlin/com/nexters/bottles/BottlesApplication.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/BottleHistory.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleHistoryRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleMatchingRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/dto/UsersCanBeMatchedDto.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/BottleService.kt
  src/main/kotlin/com/nexters/bottles/user/domain/User.kt
  src/main/kotlin/com/nexters/bottles/user/domain/UserProfile.kt
  src/main/resources/application.yml
  src/main/resources/sql/ddl/table_query.sql
Labels: feat 💡

#129 [Feature/111] 테스트용 매칭 상황
  src/main/kotlin/com/nexters/bottles/admin/controller/AdminController.kt
  src/main/kotlin/com/nexters/bottles/admin/facade/AdminFacade.kt
  src/main/kotlin/com/nexters/bottles/admin/facade/dto/ForceAfterProfileResponse.kt
  src/main/kotlin/com/nexters/bottles/admin/service/AdminService.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/LetterRepository.kt
  src/main/resources/sql/ddl/table_query.sql
Labels: admin

#138 [Feature/60] FCM 푸시 알림 기능을 구현한다
  .github/workflows/deploy-workflow.yml
  build.gradle.kts
  src/main/kotlin/com/nexters/bottles/config/FCMConfig.kt
  src/main/kotlin/com/nexters/bottles/config/SchedulerConfig.kt
  src/main/kotlin/com/nexters/bottles/notification/component/FcmClient.kt
  src/main/kotlin/com/nexters/bottles/notification/component/FcmScheduler.kt
  src/main/kotlin/com/nexters/bottles/notification/component/dto/FcmNotification.kt
  src/main/kotlin/com/nexters/bottles/notification/controller/FcmTokenController.kt
  src/main/kotlin/com/nexters/bottles/notification/domain/FcmToken.kt
  src/main/kotlin/com/nexters/bottles/notification/facade/FcmTokenFacade.kt
  src/main/kotlin/com/nexters/bottles/notification/facade/dto/FcmTokenRegisterRequest.kt
  src/main/kotlin/com/nexters/bottles/notification/repository/FcmTokenRepository.kt
  src/main/kotlin/com/nexters/bottles/notification/service/FcmTokenService.kt
  src/main/kotlin/com/nexters/bottles/user/repository/UserRepository.kt
  src/main/kotlin/com/nexters/bottles/user/service/UserService.kt
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/sql/ddl/table_query.sql
Labels: feat 💡

#142 [Fix/141] docker-compose.yml에 fcm 환경변수 추가한다
  docker-compose.yml
Labels: fix 🛠️

#144 [Fix/143] docker-compose.yml에 fcm admin 파일 volume을 설정한다
  docker-compose.yml
Labels: fix 🛠️

#149 [Feature/147] 보틀 상세 정보 API 수정 및 gradle 설정을 수정한다
  README.md
  api/build.gradle.kts
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottleDetailResponse.kt
  app/build.gradle.kts
  app/src/main/kotlin/com/nexters/bottles/app/common/component/AmazonS3FileService.kt
  app/src/main/kotlin/com/nexters/bottles/app/config/S3Config.kt
  app/src/main/resources/application-dev.yml
  app/src/main/resources/application.yml
  batch/build.gradle.kts
  batch/src/main/kotlin/com/nexters/bottles/batch/BottlesBatchApplication.kt
  build.gradle.kts
Labels: feat 💡

#156 [Feature/154] 로그인시 프로필 작성 여부 알려주기
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/KakaoSignInUpResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/SmsSignInResponse.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/UserProfile.kt
Labels: feat 💡

#152 [Feature/151] 테스트 api 분리
  api/src/main/kotlin/com/nexters/bottles/api/admin/controller/AdminController.kt
  api/src/main/kotlin/com/nexters/bottles/api/admin/facade/AdminFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/admin/service/AdminService.kt
Labels: admin

#159 [Feature/157] 핑퐁 조회 응답 데이터 추가 및 테이블을 수정한다
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottlePingPongResponse.kt
  api/src/main/resources/sql/ddl/table_query.sql
  app/src/main/kotlin/com/nexters/bottles/app/bottle/domain/Bottle.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/domain/Letter.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/LetterService.kt
Labels: feat 💡

#161 [Feature/160] 같은 분 내에 들어오는 요청은 같은 토큰 제공
  api/src/main/kotlin/com/nexters/bottles/api/admin/component/TestJwtTokenProvider.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/JwtTokenProvider.kt
Labels: feat 💡

#164 [Feature/163] 유저 프로필 생성 여부도 로그인 시 알려준다
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/KakaoSignInUpResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/SmsSignInResponse.kt
  app/src/main/kotlin/com/nexters/bottles/app/admin/service/AdminService.kt
Labels: feat 💡

#168 [Feature/162] 관리자 계정 예외 처리를 한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
Labels: admin

#169 [Feature/166] 유저 마지막 활성 시간 기록하기
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/config/AsyncConfig.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/component/event/UserApplicationEventListener.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/component/event/dto/UserApplicationEventDto.kt
  api/src/main/resources/sql/ddl/table_query.sql
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/User.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserService.kt
  app/src/main/resources/application-dev.yml
Labels: feat 💡

#173 [Feature/172] 이미지 블러 처리 효과를 강화한다.
  app/src/main/kotlin/com/nexters/bottles/app/bottle/domain/Bottle.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/common/component/ImageProcessor.kt
Labels: feat 💡

#185 [Feature/184] 핑퐁 조회 시 user id 데이터를 반환한다
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottlePingPongResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/PingPongListResponse.kt
Labels: feat 💡

#181 [Feature/180] workflow cache 적용
  .github/workflows/deploy-workflow.yml
  .github/workflows/pull-request-workflow.yml
Labels: infra 🐳

#178 [Feature/175] 유저 지역 반정규화
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
  api/src/main/resources/sql/ddl/table_query.sql
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleMatchingRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/dto/UsersCanBeMatchedDto.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/User.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserService.kt
Labels: feat 💡

#182 [Feature/171] 중단된 대화 소프트 삭제 및 핑퐁 남은 기간 데이터를 응답한다
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottlePingPongResponse.kt
  api/src/main/resources/sql/ddl/table_query.sql
  app/build.gradle.kts
  app/src/main/kotlin/com/nexters/bottles/app/bottle/domain/Bottle.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/domain/Letter.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/LetterService.kt
  batch/src/main/kotlin/com/nexters/bottles/batch/config/SchedulerConfig.kt
  batch/src/main/kotlin/com/nexters/bottles/batch/scheduler/DeleteBottleScheduler.kt
  batch/src/main/kotlin/com/nexters/bottles/batch/scheduler/FcmNotificationScheduler.kt
  batch/src/main/kotlin/com/nexters/bottles/batch/service/BottleBatchService.kt
Labels: feat 💡

#187 [Feature/186] jwt 생성시 나노초까지 같아야 같은 토큰을 발급하게 원복
  api/src/main/kotlin/com/nexters/bottles/api/admin/component/TestJwtTokenProvider.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/JwtTokenProvider.kt
Labels: feat 💡

#189 [Fix/188] 자기소개 작성 여부 조회 API를 수정한다
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
Labels: fix 🛠️

#193 [Feature/192] JwtTokenProvider 로그 심기 및 refreshToken은 balcklist 검사 제외
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/JwtTokenProvider.kt
Labels: feat 💡

#195 [Feature/194] 테스트 계정 인증 로직을 수정한다
  .github/workflows/deploy-workflow.yml
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  app/src/main/resources/application-dev.yml
  docker-compose.yml
Labels: admin

#201 [Feature/200] 유저 매칭 활성화 여부 필드 및 매칭을 활성화한다
  .github/workflows/deploy-workflow.yml
  api/src/main/resources/sql/ddl/table_query.sql
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleMatchingRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/User.kt
  app/src/main/resources/application-dev.yml
  docker-compose.yml
Labels: feat 💡

#204 [Fix/203] 매칭 시간 이전에는 매칭하지 않도록 한다
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
Labels: fix 🛠️

#207 [Feature/205] 이성과 매칭 & 자기소개 작성 안한 유저와 매칭하지 않기
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleMatchingRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
Labels: feat 💡

#216 [Fix/215] enum 대신 name 사용하도록 수정
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleMatchingRepository.kt
Labels: fix 🛠️

#209 [Feature/208] 포토 상태 추가
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottlePingPongResponse.kt
Labels: feat 💡

#218 [Fix/217] 쿼리 수정
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleMatchingRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
Labels: feat 💡

#222 feat: named parameter로 수정
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleMatchingRepository.kt
Labels: fix 🛠️

#211 [Fix/210] 매칭 유효기간 설정 수정 및 매칭 로직 수정한다
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleMatchingRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
Labels: fix 🛠️

#224 [Feature/223] 핑퐁 조회 API MatchStatus 상태값을 추가한다
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottlePingPongResponse.kt
Labels: feat 💡

#202 [Feature/150] 캐시를 적용한다
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/BottleApiEventListener.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  app/build.gradle.kts
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleCachingService.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/LetterService.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/QuestionCachingService.kt
  app/src/main/kotlin/com/nexters/bottles/app/config/CacheConfig.kt
  app/src/main/kotlin/com/nexters/bottles/app/config/CacheType.kt
Labels: feat 💡

#226 [Feature/225] 보틀 수락 및 어드민 API에 cache evict 추가한다
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/admin/service/AdminService.kt
Labels: feat 💡

#230 [Fix/229] 핑퐁 조회 API 상태값 수정한다
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottlePingPongResponse.kt
Labels: fix 🛠️

#228 [Fix/227] 매칭 쿼리를 수정한다
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleMatchingRepository.kt
Labels: fix 🛠️

#232 feat: 자기소개 작성여부 api 수정
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
Labels: feat 💡

#239 [Feature/238] 카카오/일반 양방향으로 로그인 가능하도록 한다
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserService.kt
Labels: feat 💡

#241 [Feature/236] 요청별로 userId 로그 심기
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/JwtTokenProvider.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/controller/BottleController.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/global/filter/LoggingFilter.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/controller/UserProfileController.kt
  app/src/main/resources/logback-spring.xml
Labels: feat 💡

#243 feat: 유저 프로필 작성 상태 조회
  api/src/main/kotlin/com/nexters/bottles/api/user/controller/UserProfileController.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/dto/UserProfileStatusResponse.kt
Labels: feat 💡

#237 [Feature/233] 회원 탈퇴 시 핑퐁 중이던 대화를 멈추도록 한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/AuthApplicationEventListener.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/event/DeleteUserEventDto.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleCachingService.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
Labels: fix 🛠️

#248 [Feature/247] 보틀에서 유저 eager로 조회하기
  app/src/main/kotlin/com/nexters/bottles/app/bottle/domain/Bottle.kt
Labels: feat 💡

#252 [Fix/251] 보틀 수락 시 보틀 목록 cache evict 한다
  api/src/main/kotlin/com/nexters/bottles/api/admin/facade/AdminFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/admin/service/AdminService.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/domain/Bottle.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
Labels: fix 🛠️

#254 [Fix/253] 로그아웃 시 fcm 토큰 request body null을 허용한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
Labels: fix 🛠️

#246 [Docs/177] index 추가
  api/src/main/resources/sql/ddl/table_query.sql
Labels: docs 📁

#258 [Feature/256] 일반회원가입 v2구현
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthControllerV2.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserService.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/dto/SignUpProfileRequestV2.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/dto/SignUpRequestV2.kt
Labels: feat 💡

#259 [Feature/255] 슈퍼계정의 일반회원가입 v2 흐름을 허용한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
Labels: feat 💡

#262 [Feature/261] 일반 회원가입/로그인 v2를 통합한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserService.kt
Labels: feat 💡

#266 [Feature/263] 일반 회원가입시 상태를 알려준다
  .github/workflows/deploy-workflow.yml
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthControllerV2.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/SignUpResponseV2.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/dto/UserInfoResponse.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/dto/SignInUpDtoV2.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/dto/SignInUpStep.kt
  docker-compose.yml
Labels: feat 💡

#270 [Feature/269] 슈퍼계정 탈퇴 후에도 일반 회원가입 가능
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthControllerV2.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/repository/UserRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserProfileService.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserService.kt
Labels: admin

#267 [Fix/264] 보틀 조회 시 user deleted 여부 확인 및 자기소개 없으면 매칭되지 않도록 수정한다
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/User.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/UserProfile.kt
Labels: fix 🛠️

#272 [Feature/271] 애플 로그인을 구현한다
  .github/workflows/deploy-workflow.yml
  api/build.gradle.kts
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/AppleAuthClientSecretKeyGenerator.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/JwtTokenProvider.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/AppleIdTokenPayload.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/AppleSignInUpRequest.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/AppleSignInUpResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/AppleUserInfoResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottleDetailResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottleListResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottlePingPongResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/PingPongListResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/infra/WebClientAdapter.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/dto/UserInfoResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/dto/UserProfileResponse.kt
  api/src/main/resources/sql/ddl/table_query.sql
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/User.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/enum/SignUpType.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/repository/UserRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserService.kt
  app/src/main/resources/application-dev.yml
  docker-compose.yml
Labels: feat 💡

#274 [Feature/273] 유저 정보 조회 API에 애플 로그인만 한 상태를 추가한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthControllerV2.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserService.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/dto/SignInUpStep.kt
Labels: feat 💡

#276 [Feature/275] 애플 로그인 탈퇴를 위한 client secret 값 조회 API를 구현한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/AppleRevokeResponse.kt
Labels: feat 💡

#287 [Fix/284] 애플 로그인 수정한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/JwtTokenProvider.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/ApplePublicKey.kt
  api/src/main/kotlin/com/nexters/bottles/api/infra/WebClientAdapter.kt
Labels: fix 🛠️

#286 [Feature/285] 로컬에서 dns를 못찾는 예외 로그 제거 / 애플 ClientSecret 유효시간 늘리기
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/AppleAuthClientSecretKeyGenerator.kt
  app/build.gradle.kts
Labels: feat 💡

#291 [Feature/290] 로그에 uri, 메서드 추가
  api/src/main/kotlin/com/nexters/bottles/api/global/filter/LoggingFilter.kt
Labels: feat 💡

#295 [Fix/294] fcm 토큰 등록, 삭제 메서드를 수정한다
  app/src/main/kotlin/com/nexters/bottles/app/notification/repository/FcmTokenRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/service/FcmTokenService.kt
Labels: fix 🛠️

#299 feat: 애플 로그인시 나이/성별을 필수로 받지않고, 애플로그인 유저면 유저이름 정보 조회시 응답 상태값을 변경한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/controller/UserProfileController.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/dto/SignUpProfileRequestV2.kt
Labels: feat 💡

#297 [Fix/296] 회원 탈퇴 시 보틀 중단하는 메서드를 수정한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/AuthApplicationEventListener.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
Labels: fix 🛠️

#293 [Feature/245] 상황 별 푸시 알림을 추가한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/ApplePublicKeyGenerator.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/BottleApiEventListener.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/dto/BottleAcceptEventDto.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/dto/BottleMatchEventDto.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/dto/BottleRefuseEventDto.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/dto/BottleRegisterLetterEventDto.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/dto/BottleShareContactEventDto.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/dto/BottleShareImageEventDto.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/dto/BottleStopEventDto.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/domain/Bottle.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/repository/FcmTokenRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/service/FcmTokenService.kt
  batch/src/main/kotlin/com/nexters/bottles/batch/scheduler/FcmNotificationScheduler.kt
Labels: feat 💡

#303 [Fix/301] profile status 조회 시 탈퇴한 유저는 예외 반환한다
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
Labels: fix 🛠️

#302 [Feature/300] 나이 계산시 npe나는 오류 수정
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/User.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/dto/SignUpProfileRequestV2.kt
Labels: feat 💡

#305 [Fix/304] fcm token 저장하는 메서드를 수정한다
  app/src/main/kotlin/com/nexters/bottles/app/notification/service/FcmTokenService.kt
Labels: fix 🛠️

#308 [Feature/307] 최대 파일 사이즈를 설정한다
  app/src/main/resources/application-dev.yml
Labels: feat 💡

#309 [Feature/29] 무중단 배포 환경을 구성한다
  README.md
  deploy.sh
  docker-compose.yml
Labels: infra 🐳

#315 [Fix/314] docker compose 실행 service명을 수정한다
  deploy.sh
Labels: fix 🛠️

#318 [Fix/317] 배포 스크립트 오류를 수정한다
  deploy.sh
Labels: fix 🛠️

#316 [Feature/292] 상대 유저 이름 마스킹 처리
  README.md
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/BottleApiEventListener.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/controller/UserProfileController.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/User.kt
  img.png
Labels: feat 💡

#320 [Feature/319] nginx 컨테이너 실행중이라면 다시 실행되지 않도록 한다
  deploy.sh
Labels: feat 💡

#321 [Docs/310] README 업데이트
  README.md
  img.png
Labels: docs 📁

#323 [Fix/322] 랜덤 매칭 오류를 수정한다
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
Labels: fix 🛠️

#325 [Fix/324] 호감 보낼 때 푸시 알림 전송 대상을 변경한다
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/BottleApiEventListener.kt
Labels: fix 🛠️

#326 [Feature/235] 이미지 블러 처리 로직 제거 및 마지막 랜덤 매칭 시간을 저장한다
  api/src/main/kotlin/com/nexters/bottles/api/admin/facade/AdminFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
  api/src/main/resources/sql/ddl/table_query.sql
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/common/component/ImageProcessor.kt
  app/src/main/kotlin/com/nexters/bottles/app/common/component/ImageUploader.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/User.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/UserProfile.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserProfileService.kt
Labels: feat 💡

#328 [Feature/327] 토큰 재발행 시 fcm token 등록할 수 있도록 한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/ReissueTokenRequest.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/ReissueTokenResponse.kt
Labels: feat 💡

#330 [Feature/329] 자기소개 최초 등록 시 랜덤 보틀을 하나 넣어준다
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/component/event/UserProfileApplicationEventListener.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/component/event/dto/IntroductionSaveEventDto.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserProfileService.kt
Labels: feat 💡

#332 [Feature/331] 푸시 스케줄러 app으로 임시 이동한다
  app/src/main/kotlin/com/nexters/bottles/app/config/SchedulerConfig.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/component/FcmNotificationScheduler.kt
Labels: feat 💡

#334 [Fix/333] 자기소개를 처음 작성하면 보틀 넣어주도록 수정한다
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserProfileService.kt
Labels: fix 🛠️

#336 [Fix/335] fcm 토큰 조회 시 빈 값을 제외하여 조회한다
  app/src/main/kotlin/com/nexters/bottles/app/notification/component/FcmNotificationScheduler.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/repository/FcmTokenRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/service/FcmTokenService.kt
  batch/src/main/kotlin/com/nexters/bottles/batch/scheduler/FcmNotificationScheduler.kt
Labels: fix 🛠️

#341 [Feature/340] 푸시보낼 떄 로그 심기
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/BottleApiEventListener.kt
Labels: feat 💡

#342 [Feature/337] 푸시 다른 사람에게 가는 버그 수정
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/BottleApiEventListener.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/component/FcmNotificationScheduler.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/repository/FcmTokenRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/service/FcmTokenService.kt
  batch/src/main/kotlin/com/nexters/bottles/batch/scheduler/FcmNotificationScheduler.kt
Labels: fix 🛠️

#344 feat: 토큰 쿼리 수정
  app/src/main/kotlin/com/nexters/bottles/app/notification/repository/FcmTokenRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/service/FcmTokenService.kt
Labels: fix 🛠️

#346 feat: fcm 토큰 블랭크 아닌 사람에게만 보내기
  app/src/main/kotlin/com/nexters/bottles/app/notification/service/FcmTokenService.kt
Labels: feat 💡

#348 feat: AI 기능 제거
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottlePingPongResponse.kt
Labels: feat 💡

#353 feat: 호감 표현시 푸시 반대로 가는 버그 수정
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/BottleApiEventListener.kt
Labels: fix 🛠️

#355 [Feature/354] 만료된 보틀 보여주지 않기 / fcm 토큰 업데이트 api
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/FcmUpdateRequest.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/domain/Bottle.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/component/FcmClient.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/repository/FcmTokenRepository.kt
Labels: feat 💡

#358 [Feature/357] 푸시 다건 발송 어드민
  api/src/main/kotlin/com/nexters/bottles/api/admin/controller/AdminController.kt
  api/src/main/kotlin/com/nexters/bottles/api/admin/facade/AdminFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/admin/facade/dto/PushMessageRequest.kt
Labels: admin

#364 [Feature/362] 회원가입 했을 때 자기소개 부스팅 푸시 추가
  api/src/main/kotlin/com/nexters/bottles/api/auth/event/AuthApiEventListener.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/event/dto/SignUpEventDto.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserService.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/dto/SignInUpDto.kt
Labels: feat 💡

#366 feat: 보틀 목록에서 마지막 활성 시간을 제공한다
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/BottleListResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/PingPongListResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/util/TimeConvertUtil.kt
Labels: feat 💡

#370 feat: 마지막 활성화 시간 임시 null 처리
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
Labels: feat 💡
