Repository Nexters/Bottles_BE, pull requests merged in 2024-07, with the labels that each got.

#1 [settings] Issue, PR Template을 작성한다.
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
Labels: docs 📁

#3 [Feature/2] Github Actions를 통한 CI/CD를 구축한다
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/workflows/deploy-workflow.yml
  .github/workflows/pull-request-workflow.yml
  Dockerfile
  build.gradle.kts
  deploy.sh
  docker-compose.yml
  notify_error.sh
Labels: feat 💡

#5 bug: aws 인스턴스에 환경변수 전달 안되는 문제 수정 및 docker compose 파일 db에 의존성 가지게 수정
  .github/workflows/deploy-workflow.yml
  deploy.sh
  docker-compose.yml
Labels: fix 🛠️

#11 [feature/6] 디스코드 알림에 멘션을 함께 보내도록 한다
  .github/workflows/deploy-workflow.yml
  .github/workflows/pull-request-workflow.yml
  notify_error.sh
Labels: feat 💡

#16 [Feature/15] 온보딩 선택지를 조회하는 api를 구현한다
  src/main/kotlin/com/nexters/bottles/user/controller/UserProfileController.kt
  src/main/kotlin/com/nexters/bottles/user/controller/dto/ProfileChoiceResponseDto.kt
  src/main/kotlin/com/nexters/bottles/user/facade/UserProfileFacade.kt
  src/main/kotlin/com/nexters/bottles/user/util/CityFile.kt
Labels: feat 💡

#14 [feature/12] feat: 온보딩 선택을 등록하는 API 구현
  README.md
  build.gradle.kts
  src/main/kotlin/com/nexters/bottles/BottlesApplication.kt
  src/main/kotlin/com/nexters/bottles/config/JacksonConfig.kt
  src/main/kotlin/com/nexters/bottles/config/SwaggerConfig.kt
  src/main/kotlin/com/nexters/bottles/user/controller/UserProfileController.kt
  src/main/kotlin/com/nexters/bottles/user/controller/dto/InterestDto.kt
  src/main/kotlin/com/nexters/bottles/user/controller/dto/ProfileChoiceResponseDto.kt
  src/main/kotlin/com/nexters/bottles/user/controller/dto/RegionDto.kt
  src/main/kotlin/com/nexters/bottles/user/controller/dto/RegisterProfileRequestDto.kt
  src/main/kotlin/com/nexters/bottles/user/domain/BaseEntity.kt
  src/main/kotlin/com/nexters/bottles/user/domain/User.kt
  src/main/kotlin/com/nexters/bottles/user/domain/UserProfile.kt
  src/main/kotlin/com/nexters/bottles/user/domain/enum/Gender.kt
  src/main/kotlin/com/nexters/bottles/user/facade/UserProfileFacade.kt
  src/main/kotlin/com/nexters/bottles/user/repository/UserProfileRepository.kt
  src/main/kotlin/com/nexters/bottles/user/repository/UserRepository.kt
  src/main/kotlin/com/nexters/bottles/user/repository/converter/UserProfileSelectConverter.kt
  src/main/kotlin/com/nexters/bottles/user/service/UserProfileService.kt
  src/main/kotlin/com/nexters/bottles/user/util/CityFile.kt
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/sql/table_query.sql
  src/test/kotlin/com/nexters/bottles/BottlesApplicationTests.kt
Labels: feat 💡

#18 [Feature/17] 자기소개 등록하기 API를 구현한다
  src/main/kotlin/com/nexters/bottles/user/controller/UserProfileController.kt
  src/main/kotlin/com/nexters/bottles/user/domain/UserProfile.kt
  src/main/kotlin/com/nexters/bottles/user/facade/UserProfileFacade.kt
  src/main/kotlin/com/nexters/bottles/user/facade/dto/InterestDto.kt
  src/main/kotlin/com/nexters/bottles/user/facade/dto/ProfileChoiceResponseDto.kt
  src/main/kotlin/com/nexters/bottles/user/facade/dto/RegionDto.kt
  src/main/kotlin/com/nexters/bottles/user/facade/dto/RegisterIntroductionRequestDto.kt
  src/main/kotlin/com/nexters/bottles/user/facade/dto/RegisterProfileRequestDto.kt
  src/main/kotlin/com/nexters/bottles/user/repository/UserProfileRepository.kt
  src/main/kotlin/com/nexters/bottles/user/repository/converter/QuestionAndAnswerConverter.kt
  src/main/kotlin/com/nexters/bottles/user/repository/converter/UserProfileSelectConverter.kt
  src/main/kotlin/com/nexters/bottles/user/service/UserProfileService.kt
  src/main/resources/sql/table_query.sql
Labels: feat 💡

#24 [Feature/21] 받은 보틀 목록 조회 API를 구현한다
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Bottle.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/dto/BottleDto.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/dto/BottleListResponseDto.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/BottleService.kt
  src/main/kotlin/com/nexters/bottles/config/JacksonConfig.kt
  src/main/kotlin/com/nexters/bottles/global/BaseEntity.kt
  src/main/kotlin/com/nexters/bottles/user/domain/User.kt
  src/main/kotlin/com/nexters/bottles/user/domain/UserProfile.kt
  src/main/resources/sql/table_query.sql
Labels: feat 💡

#22 [feature/19] 프로필 조회 구현
  src/main/kotlin/com/nexters/bottles/user/controller/UserProfileController.kt
  src/main/kotlin/com/nexters/bottles/user/domain/User.kt
  src/main/kotlin/com/nexters/bottles/user/facade/UserProfileFacade.kt
  src/main/kotlin/com/nexters/bottles/user/facade/dto/UserProfileResponseDto.kt
  src/main/kotlin/com/nexters/bottles/user/service/UserProfileService.kt
  src/main/kotlin/com/nexters/bottles/user/service/UserService.kt
  src/main/resources/sql/table_query.sql
Labels: feat 💡

#26 [Feature/25] 보틀 상세 정보 조회 API를 구현한다
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Bottle.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/dto/BottleDetailResponseDto.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/dto/BottleDto.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/BottleService.kt
Labels: feat 💡

#28 [Feature/27] 보틀 수락하기 API를 구현한다
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Bottle.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Letter.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Question.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/enum/PingPongStatus.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/LetterRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/QuestionRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/converter/LetterQuestionAndAnswerConverter.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/BottleService.kt
  src/main/resources/sql/table_query.sql
Labels: feat 💡

#40 [Feature/39] 보틀 거절하기 API를 구현한다
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Bottle.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/BottleService.kt
Labels: feat 💡

#42 [Feature/41] 전역적으로 예외 처리를 한다
  src/main/kotlin/com/nexters/bottles/global/exception/ErrorResponseDto.kt
  src/main/kotlin/com/nexters/bottles/global/exception/GlobalExceptionHandler.kt
Labels: feat 💡

#53 [Feature/35] 보틀 보관함 조회하는 API를 구현한다
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Bottle.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/dto/PingPongListResponseDto.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/LetterRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/BottleService.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/LetterService.kt
Labels: feat 💡

#44 [Feature/43] 핑퐁 질문 리스트 dml 작성
  src/main/resources/sql/ddl/table_query.sql
  src/main/resources/sql/dml/insert_query.sql
Labels: feat 💡

#54 [Feature/46] 편지 답변 등록하는 API를 구현한다
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Letter.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/dto/RegisterLetterRequestDto.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/BottleService.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/LetterService.kt
  src/main/resources/sql/ddl/table_query.sql
Labels: feat 💡

#55 [Feature/50] 보틀 읽음 표시 API를 구현한다
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Letter.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/LetterService.kt
Labels: feat 💡

#56 [Feature/49] 대화 중단하기 API를 구현한다
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Bottle.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
Labels: feat 💡

#51 [Feature/45] 보틀의 핑퐁 조회하기
  src/main/kotlin/com/nexters/bottles/BottlesApplication.kt
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Bottle.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/enum/PingPongStatus.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/dto/BottlePingPongResponseDto.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/BottleService.kt
  src/main/kotlin/com/nexters/bottles/user/domain/User.kt
  src/main/kotlin/com/nexters/bottles/user/domain/UserProfile.kt
  src/main/kotlin/com/nexters/bottles/user/facade/UserProfileFacade.kt
  src/main/kotlin/com/nexters/bottles/user/facade/dto/RegisterProfileRequestDto.kt
  src/main/resources/sql/ddl/table_query.sql
Labels: feat 💡

#61 [Feature/47] AWS S3 설정 및 사진 전송하기 API를 구현한다
  .github/workflows/deploy-workflow.yml
  .github/workflows/pull-request-workflow.yml
  build.gradle.kts
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Letter.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/BottleService.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/FileService.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/LetterService.kt
  src/main/kotlin/com/nexters/bottles/config/S3Config.kt
  src/main/kotlin/com/nexters/bottles/infra/AmazonS3FileService.kt
  src/main/resources/application.yml
  src/main/resources/sql/ddl/table_query.sql
Labels: feat 💡

#62 [Fix/57] 보틀 보관함 조회 시 중단된 보틀도 함께 조회하도록 수정한다
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/repository/BottleRepository.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/BottleService.kt
Labels: fix 🛠️

#72 feat: sms 발송 요청 api를 구현한다
  .github/workflows/pull-request-workflow.yml
  README.md
  docker-compose.yml
  src/main/kotlin/com/nexters/bottles/auth/component/NaverSmsEncoder.kt
  src/main/kotlin/com/nexters/bottles/auth/controller/AuthController.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/AuthFacade.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/dto/NaverSmsRequestDto.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/dto/SmsRequestDto.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/dto/SmsResponseDto.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/dto/SmsSendRequest.kt
  src/main/kotlin/com/nexters/bottles/config/WebClientConfig.kt
  src/main/kotlin/com/nexters/bottles/infra/WebClientAdapter.kt
  src/main/resources/application.yml
  src/main/resources/sql/ddl/table_query.sql
Labels: feat 💡

#79 [Feat/78] application.yml profile 수정
  src/main/resources/application.yml
Labels: feat 💡

#82 [Fix/81] 도커내에서 mysql 연결
  src/main/resources/application.yml
Labels: fix 🛠️

#84 [Fix/83] 도커 환경에서 스프링부트가 뜨지 않는 문제를 해결한다
  .github/workflows/pull-request-workflow.yml
  deploy.sh
  docker-compose.yml
  src/main/resources/application.yml
Labels: fix 🛠️

#86 [Fix/85] docker-compose.yml 오타를 수정한다
  docker-compose.yml
Labels: fix 🛠️

#87 [Feature/68] 인증/인가 기능을 구현한다
  src/main/kotlin/com/nexters/bottles/auth/component/JwtTokenProvider.kt
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/BottleService.kt
  src/main/kotlin/com/nexters/bottles/config/SwaggerConfig.kt
  src/main/kotlin/com/nexters/bottles/config/WebConfig.kt
  src/main/kotlin/com/nexters/bottles/global/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/nexters/bottles/global/exception/UnauthorizedException.kt
  src/main/kotlin/com/nexters/bottles/global/interceptor/AuthInterceptor.kt
  src/main/kotlin/com/nexters/bottles/global/interceptor/AuthRequired.kt
  src/main/kotlin/com/nexters/bottles/global/resolver/AuthUserId.kt
  src/main/kotlin/com/nexters/bottles/global/resolver/AuthUserIdArgumentResolver.kt
  src/main/kotlin/com/nexters/bottles/user/controller/UserProfileController.kt
  src/main/kotlin/com/nexters/bottles/user/domain/UserProfile.kt
  src/main/kotlin/com/nexters/bottles/user/facade/UserProfileFacade.kt
  src/main/kotlin/com/nexters/bottles/user/service/UserProfileService.kt
  src/main/kotlin/com/nexters/bottles/user/service/UserService.kt
  src/main/resources/application.yml
  src/main/resources/sql/ddl/table_query.sql
Labels: feat 💡

#96 [Feature/95] 프로필 등록시 카카오 id 추가
  src/main/kotlin/com/nexters/bottles/user/facade/UserProfileFacade.kt
  src/main/kotlin/com/nexters/bottles/user/facade/dto/RegisterProfileRequestDto.kt
  src/main/kotlin/com/nexters/bottles/user/service/UserService.kt
Labels: feat 💡

#99 [Feature/64] 일반 회원가입 API를 구현한다
  src/main/kotlin/com/nexters/bottles/auth/controller/AuthController.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/AuthFacade.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/dto/SignUpRequest.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/dto/SignUpResponse.kt
  src/main/kotlin/com/nexters/bottles/user/domain/User.kt
  src/main/kotlin/com/nexters/bottles/user/domain/enum/SignUpType.kt
  src/main/kotlin/com/nexters/bottles/user/service/UserService.kt
  src/main/resources/sql/ddl/table_query.sql
Labels: feat 💡

#103 [Feature/97] 로그아웃 기능 구현하기
  src/main/kotlin/com/nexters/bottles/auth/controller/AuthController.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/AuthFacade.kt
  src/main/kotlin/com/nexters/bottles/auth/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/nexters/bottles/auth/service/RefreshTokenService.kt
Labels: feat 💡

#105 [Feature/88] 자기소개 작성 여부 조회 API를 구현한다
  src/main/kotlin/com/nexters/bottles/user/controller/UserProfileController.kt
  src/main/kotlin/com/nexters/bottles/user/facade/UserProfileFacade.kt
  src/main/kotlin/com/nexters/bottles/user/facade/dto/ExistIntroductionResponse.kt
Labels: feat 💡

#100 [Feature/89] 사진 등록 API 수정 및 사진 공유 여부를 선택하는 API를 구현한다
  .gitignore
  src/main/kotlin/com/nexters/bottles/bottle/controller/BottleController.kt
  src/main/kotlin/com/nexters/bottles/bottle/domain/Letter.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/BottleFacade.kt
  src/main/kotlin/com/nexters/bottles/bottle/facade/dto/BottleImageShareRequest.kt
  src/main/kotlin/com/nexters/bottles/bottle/service/LetterService.kt
  src/main/kotlin/com/nexters/bottles/infra/AmazonS3FileService.kt
  src/main/kotlin/com/nexters/bottles/user/component/ImageProcessor.kt
  src/main/kotlin/com/nexters/bottles/user/component/ImageUploader.kt
  src/main/kotlin/com/nexters/bottles/user/controller/UserProfileController.kt
  src/main/kotlin/com/nexters/bottles/user/domain/UserProfile.kt
  src/main/kotlin/com/nexters/bottles/user/facade/UserProfileFacade.kt
  src/main/kotlin/com/nexters/bottles/user/service/FileService.kt
  src/main/kotlin/com/nexters/bottles/user/service/UserProfileService.kt
  src/main/resources/sql/ddl/table_query.sql
Labels: feat 💡

#106 [Feature/67] 문자 로그인 기능 구현
  src/main/kotlin/com/nexters/bottles/auth/component/JwtTokenProvider.kt
  src/main/kotlin/com/nexters/bottles/auth/controller/AuthController.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/AuthFacade.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/dto/SmsSignInRequest.kt
  src/main/kotlin/com/nexters/bottles/auth/facade/dto/SmsSignInResponse.kt
  src/main/kotlin/com/nexters/bottles/user/service/UserService.kt
Labels: feat 💡
