Repository Nexters/Bottles_BE, pull requests merged in 2024-09, with the labels that each got.

#375 [Fix/374] 사용자 탈퇴 시 진행중인 핑퐁이 중단되도록 한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/component/AuthApplicationEventListener.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
Labels: fix 🛠️

#377 [Fix/376] 핑퐁 목록 조회 쿼리를 수정한다
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleRepository.kt
Labels: fix 🛠️

#379 [Feature/379] 연락처 차단 목록 등록 및 매칭 알고리즘 반영
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/controller/UserController.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/dto/BlockContactListRequest.kt
  api/src/main/resources/sql/ddl/table_query.sql
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/BlockContact.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/repository/BlockContactRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/BlockContactListService.kt
Labels: feat 💡

#384 [Docs/383] ddl 및 문서 수정
  README.md
  api/src/main/resources/sql/ddl/table_query.sql
Labels: docs 📁

#386 [Feature/385] CD 스크립트 수정
  .github/workflows/deploy-workflow.yml
Labels: feat 💡

#387 [Feature/380] 앱 업데이트 버전을 조회하는 API를 구현한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/UpdateAppVersionResponse.kt
Labels: feat 💡

#394 [Feature/393] 애플 가입시 디폴트 성별 수정
  app/src/main/kotlin/com/nexters/bottles/app/user/service/dto/SignUpProfileRequestV2.kt
Labels: feat 💡

#388 [Feature/356] ELK를 구축한다
  .github/workflows/deploy-workflow.yml
  .github/workflows/elk-deploy-workflow.yml
  app/build.gradle.kts
  app/src/main/resources/logback-spring.xml
  docker-compose.yml
  elk/docker-compose.yml
  elk/kibana/kibana.yml
  elk/logstash/pipeline/logstash.conf
Labels: feat 💡

#397 [Fix/396] elk deploy workflow 수정한다
  .github/workflows/elk-deploy-workflow.yml
Labels: fix 🛠️

#399 [Fix/398] ELK deploy workflow 수정한다
  .github/workflows/elk-deploy-workflow.yml
Labels: fix 🛠️

#403 [Fix/402] ELK 설정을 수정한다
  .github/workflows/elk-deploy-workflow.yml
  elk/docker-compose.yml
  elk/logstash/logstash.yml
  elk/logstash/pipeline/logstash.conf
Labels: fix 🛠️

#405 [Feature/400] 알림 설정 및 조회 API 구현
  .github/workflows/pull-request-workflow.yml
  api/src/main/kotlin/com/nexters/bottles/api/user/controller/UserController.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/dto/AlimyOnOffRequest.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/dto/AlimyResponse.kt
  api/src/main/resources/sql/ddl/table_query.sql
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/UserAlimy.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/enum/AlimyType.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/repository/UserAlimyRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserAlimyService.kt
Labels: feat 💡

#409 [Feature/408] 업데이트 API 수정
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/dto/UpdateAppVersionResponse.kt
Labels: feat 💡

#411 [Feature/410] 알리미 api 수정
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/UserAlimy.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserAlimyService.kt
Labels: fix 🛠️

#413 [Feature/412] 강제 업데이트 안드로이드 버전을 추가한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
Labels: feat 💡

#416 faet: 데일리 스크럼 문구 수정
  .github/workflows/daily-scrum-notification.yml
Labels: feat 💡

#373 [Feature/367] 매칭 활성/비활성화 API를 구현한다
  api/src/main/kotlin/com/nexters/bottles/api/user/controller/UserProfileController.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/dto/ActivateMatchingRequest.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/dto/UserProfileResponse.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/component/FcmNotificationScheduler.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/component/event/UserProfileApplicationEventListener.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/repository/UserRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserProfileService.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserService.kt
  batch/src/main/kotlin/com/nexters/bottles/batch/scheduler/FcmNotificationScheduler.kt
Labels: feat 💡

#420 [Feature/417] 회원가입시 알림 자동 ON
  api/src/main/kotlin/com/nexters/bottles/api/auth/event/AuthApiEventListener.kt
Labels: feat 💡

#423 feat: 회원가입 로그인 버그 수정
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
Labels: fix 🛠️

#426 [Fix/425] 로그인하는 경우 어뷰징 validation에서 제외한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/User.kt
Labels: fix 🛠️

#428 [Feature/427] 알림 발송시 알림 설정 바라보도록 변경
  api/src/main/kotlin/com/nexters/bottles/api/bottle/event/BottleApiEventListener.kt
  app/src/main/kotlin/com/nexters/bottles/app/notification/component/FcmNotificationScheduler.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/repository/UserAlimyRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserAlimyService.kt
  batch/src/main/kotlin/com/nexters/bottles/batch/scheduler/FcmNotificationScheduler.kt
Labels: feat 💡

#430 [Feature/429] 유저 프로필 조회 API에 카카오 아이디 추가
  .github/workflows/elk-deploy-workflow.yml
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/dto/UserProfileResponse.kt
Labels: feat 💡, infra 🐳

#433 [Fix/432] 48시간 내에 재가입 방지 로직 수정
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
Labels: fix 🛠️

#447 [Feature/446] 로그를 파일로 저장하도록 한다
  .github/workflows/daily-scrum-notification.yml
  .github/workflows/deploy-workflow.yml
  app/src/main/resources/logback-spring.xml
  docker-compose.yml
Labels: infra 🐳

#453 [Docs/451] 안드로이드 다운로드 링크를 추가한다
  README.md
Labels: docs 📁

#455 [Fix/454] 탈퇴 후 재가입 로직을 수정한다
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
Labels: fix 🛠️

#459 [Feature/458] iOS 최소 버전업
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
Labels: feat 💡

#452 [Feature/445] 보틀 조회 V2 API 구현한다
  .github/workflows/daily-scrum-notification.yml
  api/src/main/kotlin/com/nexters/bottles/api/bottle/controller/BottleController.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/controller/BottleControllerV2.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacade.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/BottleFacadeV2.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/RandomBottleListResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/bottle/facade/dto/SentBottleListResponse.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/component/event/UserApplicationEventListener.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/repository/BottleRepository.kt
  app/src/main/kotlin/com/nexters/bottles/app/bottle/service/BottleService.kt
Labels: feat 💡

#461 feat: 최소버전 null처리
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
Labels: fix 🛠️

#463 [Feature/462] android 최소 버전을 올린다
  api/src/main/kotlin/com/nexters/bottles/api/auth/controller/AuthController.kt
Labels: feat 💡

#464 [Feature/456] 탈퇴 후 재가입 검증에서 보틀 멤버를 제외한다
  .github/workflows/daily-scrum-notification.yml
  .github/workflows/deploy-workflow.yml
  api/src/main/kotlin/com/nexters/bottles/api/auth/facade/AuthFacade.kt
  app/src/main/resources/application-dev.yml
  docker-compose.yml
Labels: feat 💡

#457 [Feature/449] 이미지 3장 올리는 API 구현
  api/src/main/kotlin/com/nexters/bottles/api/user/controller/UserProfileController.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/controller/UserProfileControllerV2.kt
  api/src/main/kotlin/com/nexters/bottles/api/user/facade/UserProfileFacadeV2.kt
  api/src/main/resources/sql/ddl/table_query.sql
  app/src/main/kotlin/com/nexters/bottles/app/user/domain/UserProfile.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/repository/converter/ImagesConverter.kt
  app/src/main/kotlin/com/nexters/bottles/app/user/service/UserProfileService.kt
Labels: feat 💡
